on:
  push:
    branches:
      - dev
  workflow_dispatch:
  
jobs:
  run_pull:
    name: run pull
    runs-on: ubuntu-latest
    
    steps:
    - name: connect and pull
      run: ssh ${{ SSH_PRIVATE_KEY.SSH_USER }}@${{ SSH_PRIVATE_KEY.SSH_HOST }} "cd ${{ SSH_PRIVATE_KEY.WORK_DIR }} && git checkout ${{ SSH_PRIVATE_KEY.MAIN_BRANCH }} && git pull && mkdir /srv/test"
