on:
  push:
    branches:
      - staging
  workflow_dispatch:
  
jobs:
  build_artifact:
    name: build artifact
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: 17
    - name: Build with Maven
      run: mvn -B package --file pom.xml
  
  run_pull:
    name: run pull
    runs-on: ubuntu-latest
    
    steps:
    - name: Install SSH Key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        known_hosts: 'just-a-placeholder-so-we-dont-get-errors'
    - name: Adding Known Hosts
      run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts  
    - name: connect and pull      
      run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd ${{ secrets.WORK_DIR }} && git checkout ${{ secrets.MAIN_BRANCH }} && git pull"
    - name: npm build
      run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd ${{ secrets.WORK_DIR }}/frontend && npm i"
    - name: restart frontend.service
      run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "/srv/claim-scripts/claim-frontend-restart.sh"
    - name: restart backend.service     
      run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "/srv/claim-scripts/claim-restart.sh"
