on:
  push:
    branches:
      - dev
  workflow_dispatch:    
  
jobs:
  run_pull:
    name: run pull
    runs-on: ubuntu-latest
    
    steps:
    - name: test print
      run: echo ${{ secrets.TEST_SECRET }}
